fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/Adaptavist/puppet-stdlib"
    logstashforwarder:
      repo: "https://github.com/Adaptavist/puppet-logstashforwarder"
    logrotate:
      repo: "https://github.com/Adaptavist/puppet-logrotate"
    concat:
      repo: "https://github.com/Adaptavist/puppet-concat"
  symlinks:
    logstash_forwarder_config: "#{source_dir}"
